local L = LibStub("AceLocale-3.0"):NewLocale("Deadpool", "ruRU", false)

if L then

L["DEADPOOL_WELCOME"] = "Введите /deadpool, чтобы открыть Dead Pool."

L["SPACE_BEFORE_DOT"] = ""

L["GENERAL_SECTION"] = "Общие настройки"
L["NOTIFICATIONS_SECTION"] = "Настройки уведомлений"
L["ENABLE_NOTIFICATIONS_IN_BOSS_FIGHTS"] = "Во время боёв с боссами"
L["ENABLE_NOTIFICATIONS_IN_BOSS_FIGHTS_DESC"] = "Включает/отключает уведомления во время боёв с боссами"
L["ENABLE_NOTIFICATIONS_IN_BOSS_FIGHTS"] = "Во время %s"
L["ENABLE_NOTIFICATIONS_IN_BOSS_FIGHTS_DESC"] = "Включает / отключает уведомления во время %s"
L["ENABLE_SOUND"] = "Включить звуки"
L["ENABLE_SOUND_DESC"] = "Включает/отключает звуки Dead Pool"
L["ENABLE_REMINDER"] = "Включить напоминание"
L["ENABLE_REMINDER_DESC"] = "Включает/отключает напоминание во время проверки готовности"
L["ENABLE_DEATH_ANNOUNCE"] = "Включить объявление о смерти"
L["ENABLE_DEATH_ANNOUNCE_DESC"] = "Включает/отключает окно объявления о смерти"
L["ENABLE_DEATH_QUOTES"] = "Включить цитаты о смерти"
L["ENABLE_DEATH_QUOTES_DESC"] = "Включает/отключает цитаты НПС о смерти, когда вы умираете"
L["ENABLE_ACHIEVEMENT_ANNOUNCE"] = "Включить достижения"
L["ENABLE_ACHIEVEMENT_ANNOUNCE_DESC"] = "Включает/отключает окно объявления о достижениях"
L["ENABLE_MODEL_POPUP"] = "Потеря одежды"
L["ENABLE_MODEL_POPUP_DESC"] = "Включает/отключает отображение персонажа, потерявшего предмет одежды, рядом с окном Dead Pool"
L["MODEL_POPUP_SIDE"] = "Позиция модели"
L["MODEL_POPUP_SIDE_DESC"] = "Определяет сторону, на которой будет отображаться персонаж, потерявший предмет одежды"
L["MODEL_POPUP_SIDE_LEFT"] = "Слева"
L["MODEL_POPUP_SIDE_RIGHT"] = "Справа"
L["ENABLE_MINIMAPBUTTON"] = "Кнопка на миникарте"
L["ENABLE_MINIMAPBUTTON_DESC"] = "Показывает/скрывает кнопку на миникарте"
L["ENABLE_BETBUTTON"] = "Кнопка ставки на рамках юнитов"
L["ENABLE_BETBUTTON_DESC"] = "Показывает/скрывает кнопку ставки на рамках юнитов группы"
L["ENABLE_TUTO"] = "Обучение"
L["ENABLE_MENUTUTO"] = "Подсказки"
L["ENABLE_TUTO_DESC"] = "Показывает/скрывает сообщения помощи"
L["RULES_SECTION"] = "Правила"
L["ENABLE_TRULY_UNEQUIP_ITEMS"] = "Реально снимать предметы"
L["ENABLE_TRULY_UNEQUIP_ITEMS_ENABLED"] = "Реально снимает предметы"
L["ENABLE_TRULY_UNEQUIP_ITEMS_DESC"] = "Включает/отключает реальное помещение брони вашего персонажа в инвентарь при обмене одежды на жетоны."
L["ENABLE_TRULY_UNEQUIP_ITEMS_TOOLTIP"] = "Включает/отключает реальное помещение брони вашего персонажа в инвентарь при обмене одежды на жетоны."
L["NEVER_TRULY_UNEQUIP_ITEMS_TOOLTIP"] = "Блокирует режим '%s' и предотвращает его предложение другими игроками."
L["ENABLE_SAVING_DATA_AFTER_LEAVING_GROUP"] = "Сохранение данных"
L["ENABLE_SAVING_DATA_AFTER_LEAVING_GROUP_DESC"] = "Включает/отключает сохранение данных. Создатель следующей группы может продолжить сессию азартной игры."
L["WINDOW_SECTION"] = "Настройки окна Dead Pool"
L["LOCAL_WINDOW_OPTIONS"] = "Настройки только для этого персонажа"
L["LOCAL_WINDOW_OPTIONS_DESC"] = "Настройки окна ниже и его позиция применяются только к этому персонажу."
L["HIDE_IN_COMBAT"] = "Скрывать в бою"
L["HIDE_IN_COMBAT_DESC"] = "Скрывает окно Dead Pool в бою"
L["PLAYER_FIRST"] = "Игрок первым"
L["PLAYER_FIRST_DESC"] = "Персонаж игрока отображается первым в списке."
L["BET_REMINDER"] = "Напоминание"
L["BET_REMINDER_DESC"] = "Когда начинается проверка готовности, Dead Pool напоминает вам сделать ставку."
L["DEADPOOLFRAME_ALPHA"] = "Прозрачность Dead Pool"
L["DEADPOOLFRAME_LINEHEIGHT"] = "Высота строк"
L["ROSTER_SECTION"] = "Настройки списка персонажей"
L["ADMIN_SECTION"] = "Административные настройки"
L["TELL_ANNOUNCER"] = "Сообщить диктору"
L["TELL_ANNOUNCER_DESC"] = "Сообщает имя диктора при объявлении нового звания."
L["GUILD_CHAT_ANNOUNCE"] = "Уведомления в гильдейском канале"
L["GUILD_CHAT_ANNOUNCE_DESC"] = "Отправляет уведомления о новых званиях в гильдейский канал."
L["NOT_ADMIN_ERROR"] = "Ваш уровень администрирования Dead Pool недостаточен для этого действия."
L["NOT_ENOUGH_CREDITS"] = "Недостаточно фишек для принятия этой ставки. Хотите снять %d |4предмет одежды:предметов одежды;? (%s за каждый снятый предмет)"
L["TRULY_UNEQUIP_ITEMS"] = "%s включил режим |cFFFFFF00Реально снимать предметы|r. Хотите тоже его включить?|n|n|cFFFF0000Одежда, обменянная на жетоны, будет помещена в ваш инвентарь.|r"
L["DEADPOOL_SELL_ITEM_WARNING"] = "Пока включён режим |cFFFFFF00Реально снимать предметы|r, этот предмет нельзя продать. Хотите отключить режим |cFFFFFF00Реально снимать предметы|r?"
L["NOT_ENOUGH_ITEMS"] = "У вас больше нет достаточного количества одежды."
L["UNIT_IN_COMBAT"] = "Этот персонаж находится в бою, подождите, пока он закончит сражение, чтобы сделать ставку."
L["SELF_BET_NOT_ALLOWED"] = "Вы не можете делать ставку на себя."
L["EMPTY_BANK"] = "Банк пуст. Вы не можете его сорвать."
L["DEADPOOL_SOLEILBET"] = "Солейл — ваша богиня. Ставка против неё заставляет вас терять предмет одежды."
L["DEADPOOL_VERSION_UPDATE"] = "Пожалуйста, обновите %s: Новые правила."
L["DEADPOOL_VERSION_UPDATE_DESC"] = "Новая версия %s вносит изменения в правила. Обновите, чтобы всё работало корректно."

L["ANNOUNCEDEADPOOLSESSIONBUTTON_TOOLTIP"] = "Журнал результатов"
L["ANNOUNCEDEADPOOLSESSIONBUTTON_TOOLTIPDETAIL"] = "Показывает/скрывает окно журнала результатов."

L["LOCKBUTTON_TOOLTIP"] = "Заблокировать"
L["LOCKBUTTON_TOOLTIPDETAIL"] = "Блокирует/разблокирует окно."

L["NO_SELECTED_CHARACTER"] = "Персонаж не выбран"

L["MINIMAP_TOOLTIP1"] = "ЛКМ — показать/скрыть Dead Pool."
L["MINIMAP_TOOLTIP2"] = "ПКМ — открыть панель настроек."

L["MENUOPTIONS_TOOLTIP"] = "Настройки Dead Pool"
L["MENUOPTIONS_TOOLTIPDETAIL"] = "Изменить настройки Dead Pool."

L["DEADPOOLLOGS_DIED0"] = " умер."
L["DEADPOOLLOGS_DIED1"] = " умер."
L["DEADPOOLLOGS_HASBETANDDIED"] = "Банк забирает 1 предмет одежды у %s."
L["DEADPOOLLOGS_NOWINNER"] = "Никто не выигрывает на стандартных ставках."
L["DEADPOOLLOGS_THEBANK"] = "Банк"
L["DEADPOOLLOGS_WINS"] = " выигрывает "
L["DEADPOOLLOGS_COLLECTS"] = " собирает "
L["DEADPOOLLOGS_CHIPS"] = "%s!"
L["DEADPOOLLOGS_BANKCHIPS"] = "%s из банка!"

L["DEADPOOLCOLLUMNS_CHARACTER"] = "Персонаж"
L["DEADPOOLCOLLUMNS_NEXTDEATHBETS"] = "Ставки на следующую смерть"
L["DEADPOOLCOLLUMNS_ODDS"] = "Коэффициенты"
L["DEADPOOLCOLLUMNS_WHOM_ODDS"] = "Коэффициенты %s"
L["DEADPOOLCOLLUMNS_BET"] = "Ставка"
L["DEADPOOLCOLLUMNS_MODEL"] = "Модель"
L["DEADPOOLCOLLUMNS_STATS"] = "Статистика"
L["DEADPOOLCOLLUMNS_STATS_WINS"] = "Победы"
L["DEADPOOLCOLLUMNS_STATS_FIRSTDEATH"] = "Умер первым"
L["DEADPOOLCOLLUMNS_STATS_CREDITSGAIN"] = "Доходы"
L["DEADPOOLCOLLUMNS_STATS_LOSTITEMS"] = "Снятые предметы одежды"
L["DEADPOOLCOLLUMNS_STATS_DEATHS"] = "Смерти"
L["DEADPOOLCOLLUMNS_STATS_DEATHSONBOSS"] = "Смерти в бою с боссом"
L["DEADPOOLCOLLUMNS_STATS_EARNINGS"] = "Заработок"
L["DEADPOOLCOLLUMNS_STATS_LOSSES"] = "Потери"

L["DEADPOOLUI_PLAYINGDEADPOOL"] = "Игра в Dead Pool %s"
L["DEADPOOLUI_BETSONNEXTDEATH"] = "Ставка на следующую смерть"
L["DEADPOOLUI_CHIPS"] = "Фишки"
L["DEADPOOLUI_CHIPS_TOOLTIP"] = "Ваши фишки"
L["DEADPOOLUI_CHIPS_TOOLTIPDETAIL"] = "Количество фишек в вашем владении"
L["DEADPOOLUI_CHIPS_TOOLTIPDETAILGREEN"] = ""
L["DEADPOOLUI_BANK"] = "Банк"
L["DEADPOOLUI_BANK_TOOLTIP"] = "Фишки банка"
L["DEADPOOLUI_BANK_TOOLTIPDETAIL"] = "Количество фишек в банке"
L["DEADPOOLUI_BANK_TOOLTIPDETAILGREEN"] = "Если никто не выигрывает, ставки переходят в банк.|nПопробуйте уникальную ставку, чтобы выиграть содержимое банка."
L["DEADPOOLUI_BETS"] = "Ставки"
L["DEADPOOLUI_BETS_TOOLTIP"] = "Общие ставки"
L["DEADPOOLUI_BETS_TOOLTIPDETAIL"] = "Общее количество фишек, поставленных игроками"
L["DEADPOOLUI_BETS_TOOLTIPDETAILGREEN"] = ""
L["DEADPOOLUI_RESULTS"] = "Результат"
L["DEADPOOLUI_WINNER"] = "Лидирующий игрок"
L["DEADPOOLUI_WINNER_NONE"] = "Нет"

L["DEADPOOLUI_BET"] = "Текущие коэффициенты на смерть этого персонажа "
L["DEADPOOLUI_BET2"] = "позволяют вернуть "
L["DEADPOOLUI_BET3"] = " раз вашу ставку."
L["DEADPOOLUI_BET4"] = "Ваш потенциальный выигрыш: "
L["DEADPOOLUI_BET5"] = "Ваша ставка изменит коэффициенты."
L["DEADPOOLUI_BET6"] = "Вы ставите на этого персонажа, чтобы сорвать банк."
L["DEADPOOLUI_BET7"] = "Вы поставили %s%s на этого персонажа."

L["DEADPOOLUI_NOMORECHIPS"] = "У вас больше нет фишек."
L["DEADPOOLUI_MAXBETS"] = "Вы можете поставить только на %d |4персонажа:персонажей; (зависит от размера группы)."
L["DEADPOOLUI_BETSCHANGEDONCHAR"] = "Ставки на вас изменились."

L["DEADPOOLMENU_BET"] = "Стандартная ставка (ограничена по количеству)"
L["DEADPOOLMENU_ADD"] = "Добавить"
L["DEADPOOLMENU_ALL"] = "Поставить всё, что у меня есть"
L["DEADPOOLMENU_REMOVE"] = "Снять ставку"
L["DEADPOOLMENU_BANKBET"] = "Сорвать банк"
L["DEADPOOLMENU_UNIQUE"] = "Уникальная ставка (бесплатно)"
L["DEADPOOLMENU_OPTIONS"] = "Настройки"

L["DEADPOOLTUTO_TUTO1"] = "Добро пожаловать в Dead Pool!|nКто, по-вашему, следующий отправится на тот свет? Чтобы сделать ставку, кликните на стопку фишек персонажа и выберите ставку."
L["DEADPOOLTUTO_TUTO2"] = "Отлично! Теперь осталось только терпеливо ждать следующего неудачного случая и выиграть ставку!"
L["DEADPOOLTUTO_TUTO3"] = "Ну что ж... вижу, это не заняло много времени. Проверьте результаты в главном окне чата. Не забудьте снова поставить! Несчастные случаи происходят так быстро..."
L["DEADPOOLTUTO_TUTO4"] = "Да, я забыл. Вы не можете ставить против себя. Это некрасиво!"
L["DEADPOOLTUTO_TUTO5"] = "Делайте ставки между боями. Советую оставаться сосредоточенным, банк забирает предмет одежды у неуклюжих игроков, которые погибают!"
L["DEADPOOLTUTO_TUTO6"] = "Присоединяясь к группе, вы вступаете в Dead Pool этой группы. Ваши ставки и жетоны сбрасываются."
L["DEADPOOLTUTO_TUTO7"] = "Хотите попытаться сорвать банк? Для этой ставки выбирайте только одного персонажа."

L["DEADPOOLTUTO_MINIMIZE"] = "Вы можете свернуть окно Dead Pool."
L["DEADPOOLTUTO_SELFBET"] = "Вы не можете ставить на себя, только на других персонажей в вашей группе."
L["DEADPOOLTUTO_BET"] = "Вы собираетесь поставить на следующего персонажа, который умрёт."
L["DEADPOOLTUTO_BET1"] = "Вы можете добавить фишку на этого персонажа."
L["DEADPOOLTUTO_BET5"] = "Вы можете добавить фишки на этого персонажа. Настройте количество с помощью ползунка."
L["DEADPOOLTUTO_BETTOMUCH"] = "Если у вас недостаточно фишек, Dead Pool предложит обменять одежду на дополнительные фишки."
L["DEADPOOLTUTO_BETALL"] = "Вы можете поставить все оставшиеся фишки на этого персонажа сразу."
L["DEADPOOLTUTO_BETREMOVE"] = "Вы можете снять свою ставку с этого персонажа."
L["DEADPOOLTUTO_UNIQUEBET"] = "У вас больше нет фишек или одежды, но вы можете сорвать банк!|n|nЭта ставка бесплатна, но вы можете выбрать только одного персонажа.|n|nВы получите содержимое банка в виде одежды и фишек."
L["DEADPOOLTUTO_BANKER"] = "Галливикс и спутники подземелий тоже могут участвовать в ставках."
L["DEADPOOLTUTO_BANKERBET"] = "Попросите их сделать ставку, они выберут, на кого поставить."
L["DEADPOOLTUTO_BANKERHASBET"] = "Он уже выбрал свою ставку, жребий брошен!"
L["DEADPOOLTUTO_BOSS"] = "Если все игроки Dead Pool находятся в вашем рейдовом подземелье и рейд соответствует вашему уровню, вы можете ставить на смерть следующего босса!"

L["NEW_TITLE_FOR"] = "Новое звание для %s"
L["DEADPOOL_ACHIEVEMENT_WINS"] = "Серия побед"
L["DEADPOOL_ACHIEVEMENT_WINS_DESC"] = "Станьте первым, кто выиграет %s раз в одной игре."
L["DEADPOOL_ACHIEVEMENT_FIRSTDEATH"] = "Хрупкий"
L["DEADPOOL_ACHIEVEMENT_FIRSTDEATH_DESC"] = "Станьте первым, кто умрёт первым %s раз в одной игре."
L["DEADPOOL_ACHIEVEMENT_CREDITSBALACE"] = "Набоб"
L["DEADPOOL_ACHIEVEMENT_CREDITSBALACE_DESC"] = "Станьте первым, кто заработает %s жетонов в одной игре."
L["DEADPOOL_ACHIEVEMENT_LOSTITEMS"] = "Совсем голый"
L["DEADPOOL_ACHIEVEMENT_LOSTITEMS_DESC"] = "Станьте первым, кто потеряет всю одежду в одной игре."
L["DEADPOOL_ACHIEVEMENT_SOLEILBET"] = "Солейл святотатец"
L["DEADPOOL_ACHIEVEMENT_SOLEILBET_DESC"] = "Станьте первым, кто поставит %s раз на смерть %s и потеряет %s предметов одежды в качестве наказания в одной игре."

L["MAKE_BANKER_PLAY"] = "Заставить %s сделать ставку"
L["MAKE_FOLLOWERS_PLAY"] = "и спутников"
L["BANKER_BET"] = "%s\nпоставил на %s."
L["BANKER_NO_CHIPS"] = "%s\nбольше нет фишек."

L["NEXT_BOSS"] = "Следующий босс"

end
