local L = LibStub("AceLocale-3.0"):NewLocale("Deadpool", "enUS", true)

if L then

L["DEADPOOL_WELCOME"] = "Type /deadpool to open Dead Pool."

L["SPACE_BEFORE_DOT"] = ""

L["GENERAL_SECTION"] = "General options"
L["NOTIFICATIONS_SECTION"] = "Notifications options"
L["ENABLE_NOTIFICATIONS_IN_BOSS_FIGHTS"] = "During Boss fights"
L["ENABLE_NOTIFICATIONS_IN_BOSS_FIGHTS_DESC"] = "Enables / disables notifications during Boss fights"
L["ENABLE_SOUND"] = "Enable Dead Pool sounds"
L["ENABLE_SOUND_DESC"] = "Enables / disables Dead Pool sounds"
L["ENABLE_REMINDER"] = "Enable reminder"
L["ENABLE_REMINDER_DESC"] = "Enables / disables the reminder during Ready Check"
L["ENABLE_DEATH_ANNOUNCE"] = "Enable Death Announce"
L["ENABLE_DEATH_ANNOUNCE_DESC"] = "Enables / disables the Death Announce window"
L["ENABLE_DEATH_QUOTES"] = "Enable Death Quotes"
L["ENABLE_DEATH_QUOTES_DESC"] = "Enables / disables NPC Death Quotes when you die"
L["ENABLE_ACHIEVEMENT_ANNOUNCE"] = "Enable Achievements"
L["ENABLE_ACHIEVEMENT_ANNOUNCE_DESC"] = "Enables / disables the Achievements Announce window"
L["ENABLE_MODEL_POPUP"] = "Clothing lost"
L["ENABLE_MODEL_POPUP_DESC"] = "Enables / disables the display of the character who just lost an item of clothing next to the Dead Pool window"
L["MODEL_POPUP_SIDE"] = "Model positionning"
L["MODEL_POPUP_SIDE_DESC"] = "Defines the side where the character who just lost an item of clothing will be displayed"
L["MODEL_POPUP_SIDE_LEFT"] = "Left"
L["MODEL_POPUP_SIDE_RIGHT"] = "Right"
L["ENABLE_MINIMAPBUTTON"] = "Minimap button"
L["ENABLE_MINIMAPBUTTON_DESC"] = "Shows / hides Minimap button"
L["ENABLE_BETBUTTON"] = "Unit frames bet button"
L["ENABLE_BETBUTTON_DESC"] = "Shows / hides bet button on group unit frames"
L["ENABLE_TUTO"] = "Tutorials"
L["ENABLE_MENUTUTO"] = "Help tips"
L["ENABLE_TUTO_DESC"] = "Shows / hides help messages"
L["RULES_SECTION"] = "Rules"
L["ENABLE_TRULY_UNEQUIP_ITEMS"] = "Truly unequip items"
L["ENABLE_TRULY_UNEQUIP_ITEMS_DESC"] = "Enables / disables truly putting your character's armor items in the inventory when exchanging clothing for tokens."
L["ENABLE_SAVING_DATA_AFTER_LEAVING_GROUP"] = "Data saving"
L["ENABLE_SAVING_DATA_AFTER_LEAVING_GROUP_DESC"] = "Enables / disables data saving. The creator of the next group can continue the gambling session."
L["WINDOW_SECTION"] = "Dead Pool window options"
L["LOCAL_WINDOW_OPTIONS"] = "Options for this character only"
L["LOCAL_WINDOW_OPTIONS_DESC"] = "The window options below and position only apply for this character."
L["HIDE_IN_COMBAT"] = "Hide in combat"
L["HIDE_IN_COMBAT_DESC"] = "Hide Dead Pool window in combat"
L["PLAYER_FIRST"] = "Player first"
L["PLAYER_FIRST_DESC"] = "The player's character appears first in the list."
L["BET_REMINDER"] = "Reminder"
L["BET_REMINDER_DESC"] = "When a ready check is initiated, Deadpool reminds you to bet."
L["DEADPOOLFRAME_ALPHA"] = "Dead Pool alpha"
L["DEADPOOLFRAME_LINEHEIGHT"] = "Lines height"
L["ROSTER_SECTION"] = "Character list options"
L["ADMIN_SECTION"] = "Administration options"
L["TELL_ANNOUNCER"] = "Tell announcer"
L["TELL_ANNOUNCER_DESC"] = "Tells the name of announcer while announcing a new title."
L["GUILD_CHAT_ANNOUNCE"] = "Notifications on guild channel"
L["GUILD_CHAT_ANNOUNCE_DESC"] = "Sends new titles notifications in the guild channel."
L["NOT_ADMIN_ERROR"] = "Your Dead Pool administration level is not high enough to do this."
L["NOT_ENOUGH_CREDITS"] = "Not enough chips to accept this bet. Do you want to take %d |4item of clothing:items of clothing; off? (%s for each item removed)"
L["TRULY_UNEQUIP_ITEMS"] = "%s has enable the 'Truly unequip items' mode. Do you want to enable it too?|n|n|cFFFF0000Clothing exchanged for tokens will be put in your inventory.|r"
L["NOT_ENOUGH_ITEMS"] = "You do not have enough clothes anymore."
L["UNIT_IN_COMBAT"] = "This character is in combat, wait for him to sort of fight to bet."
L["SELF_BET_NOT_ALLOWED"] = "You cannot bet on yourself."
L["EMPTY_BANK"] = "The Bank is empty. You cannot burst it."
L["DEADPOOL_SOLEILBET"] = "Sole\195\174l is your goddess. Bet against her makes you lose a item of clothing."

L["ANNOUNCEDEADPOOLSESSIONBUTTON_TOOLTIP"] = "Results logs"
L["ANNOUNCEDEADPOOLSESSIONBUTTON_TOOLTIPDETAIL"] = "Shows / hides results logs window."

L["LOCKBUTTON_TOOLTIP"] = "Lock"
L["LOCKBUTTON_TOOLTIPDETAIL"] = "Locks / unlocks the window."

L["NO_SELECTED_CHARACTER"] = "No selected character"

L["MINIMAP_TOOLTIP1"] = "Left click to show/hide Dead Pool."
L["MINIMAP_TOOLTIP2"] = "Right click to open options panel."

L["MENUOPTIONS_TOOLTIP"] = "Dead Pool options"
L["MENUOPTIONS_TOOLTIPDETAIL"] = "Change Dead Pool options."

L["DEADPOOLLOGS_DIED0"] = " died."
L["DEADPOOLLOGS_DIED1"] = " died."
L["DEADPOOLLOGS_HASBETANDDIED"] = "The bank recovers 1 item of clothing on %s."
L["DEADPOOLLOGS_NOWINNER"] = "Nobody wins on standard bets."
L["DEADPOOLLOGS_THEBANK"] = "The Bank"
L["DEADPOOLLOGS_WINS"] = " wins "
L["DEADPOOLLOGS_COLLECTS"] = " collects "
L["DEADPOOLLOGS_CHIPS"] = "%s!"
L["DEADPOOLLOGS_BANKCHIPS"] = "%s from the bank!"

L["DEADPOOLCOLLUMNS_CHARACTER"] = "Character"
L["DEADPOOLCOLLUMNS_NEXTDEATHBETS"] = "Next death bets"
L["DEADPOOLCOLLUMNS_ODDS"] = "Odds"
L["DEADPOOLCOLLUMNS_BET"] = "Bet"
L["DEADPOOLCOLLUMNS_MODEL"] = "Model"
L["DEADPOOLCOLLUMNS_STATS"] = "Stats"
L["DEADPOOLCOLLUMNS_STATS_WINS"] = "Victories"
L["DEADPOOLCOLLUMNS_STATS_FIRSTDEATH"] = "Dead first"
L["DEADPOOLCOLLUMNS_STATS_CREDITSGAIN"] = "Gains"
L["DEADPOOLCOLLUMNS_STATS_LOSTITEMS"] = "Items of clothing removed"
L["DEADPOOLCOLLUMNS_STATS_DEATHS"] = "Deaths"
L["DEADPOOLCOLLUMNS_STATS_DEATHSONBOSS"] = "Deaths on boss fight"
L["DEADPOOLCOLLUMNS_STATS_EARNINGS"] = "Earnings"
L["DEADPOOLCOLLUMNS_STATS_LOSSES"] = "Losses"

L["DEADPOOLUI_PLAYINGDEADPOOL"] = "Playing Dead Pool %s"
L["DEADPOOLUI_BETSONNEXTDEATH"] = "Bet on next death"
L["DEADPOOLUI_CHIPS"] = "Chips"
L["DEADPOOLUI_CHIPS_TOOLTIP"] = "Your chips"
L["DEADPOOLUI_CHIPS_TOOLTIPDETAIL"] = "Number of chips in your possession"
L["DEADPOOLUI_CHIPS_TOOLTIPDETAILGREEN"] = ""
L["DEADPOOLUI_BANK"] = "Bank"
L["DEADPOOLUI_BANK_TOOLTIP"] = "Bank chips"
L["DEADPOOLUI_BANK_TOOLTIPDETAIL"] = "Number of chips in the Bank"
L["DEADPOOLUI_BANK_TOOLTIPDETAILGREEN"] = "If no one wins, the bets go into the Bank.|nTry a unique gamble to win the contents of the Bank."
L["DEADPOOLUI_BETS"] = "Bets"
L["DEADPOOLUI_BETS_TOOLTIP"] = "Total bets"
L["DEADPOOLUI_BETS_TOOLTIPDETAIL"] = "Total number of chips wagered by players"
L["DEADPOOLUI_BETS_TOOLTIPDETAILGREEN"] = ""
L["DEADPOOLUI_RESULTS"] = "Result"
L["DEADPOOLUI_WINNER"] = "Player in the lead"
L["DEADPOOLUI_WINNER_NONE"] = "None"

L["DEADPOOLUI_BET"] = "The current odds on the death of this character "
L["DEADPOOLUI_BET2"] = "allows to recover "
L["DEADPOOLUI_BET3"] = " times the stake."
L["DEADPOOLUI_BET4"] = "Your potential gain: "
L["DEADPOOLUI_BET5"] = "Your bet will modify the odds."
L["DEADPOOLUI_BET6"] = "You bet on this character to burst the Bank."
L["DEADPOOLUI_BET7"] = "You bet %s%s on this character."

L["DEADPOOLUI_NOMORECHIPS"] = "You have no more chips."
L["DEADPOOLUI_MAXBETS"] = "You only can bet on %d |4character:characters; (depends on group size)."
L["DEADPOOLUI_BETSCHANGEDONCHAR"] = "The bets on you have changed."

L["DEADPOOLMENU_BET"] = "Standard Bet (limited in number)"
L["DEADPOOLMENU_ADD"] = "Add"
L["DEADPOOLMENU_ALL"] = "Put everything I've got"
L["DEADPOOLMENU_REMOVE"] = "Remove the bet"
L["DEADPOOLMENU_BANKBET"] = "Burst the Bank"
L["DEADPOOLMENU_UNIQUE"] = "Unique gamble (toll-free)"
L["DEADPOOLMENU_OPTIONS"] = "Options"

L["DEADPOOLTUTO_TUTO1"] = "Welcome to the Dead Pool!|nWho do you think will be next to kick the bucket? To bet, click on a character's stack of chips and choose your bet."
L["DEADPOOLTUTO_TUTO2"] = "Perfect ! All we have to do now is wait patiently for the next stroke of bad luck and win the bet!"
L["DEADPOOLTUTO_TUTO3"] = "Well, well ... I see it did not take long. Check the results in the main chat window. Don't forget to bet again! Accidents happen so fast ..."
L["DEADPOOLTUTO_TUTO4"] = "Yes, I forgot. You cannot bet against yourself. It's not a pretty picture!"
L["DEADPOOLTUTO_TUTO5"] = "Place your bets between combats. I advise you to stay focused, the bank recovers an item of clothing on the clumsy bettors who are killed!"
L["DEADPOOLTUTO_TUTO6"] = "When you join a group, you join the Dead Pool of that group. Your bets and tokens are reset."
L["DEADPOOLTUTO_TUTO7"] = "Want to try to burst the Bank? For this bet, you choose only one character."

L["DEADPOOLTUTO_MINIMIZE"] = "You can minimize the Dead Pool window."
L["DEADPOOLTUTO_SELFBET"] = "You cannot bet on yourself, only on other characters in your group."
L["DEADPOOLTUTO_BET"] = "You are going to bet on the next character who will die."
L["DEADPOOLTUTO_BET1"] = "You can add a chip on this character."
L["DEADPOOLTUTO_BET5"] = "You can add chips on this character. Adjust the number with the slider."
L["DEADPOOLTUTO_BETTOMUCH"] = "If you do not have enough chips, Dead Pool will offer you to exchange clothes for additional chips."
L["DEADPOOLTUTO_BETALL"] = "You can bet all your remaining chips on this character at once."
L["DEADPOOLTUTO_BETREMOVE"] = "You can withdraw your bet on this character."
L["DEADPOOLTUTO_UNIQUEBET"] = "You have no more chips or clothes but you can burst the bank!|n|nThis bet is free but you can only choose one character.|n|nYou earn what is in the bank in the form of clothes and chips."
L["DEADPOOLTUTO_BANKER"] = "Gallywix and also Dungeon followers can participate in betting."
L["DEADPOOLTUTO_BANKERBET"] = "Ask them to bet, they will choose which character they want to bet on."
L["DEADPOOLTUTO_BANKERHASBET"] = "He has already chosen his bet, the die is cast!"
L["DEADPOOLTUTO_BOSS"] = "If all Dead Pool players are in your raid instance and that raid is at your level, you can bet on the death of the next boss!"

L["NEW_TITLE_FOR"] = "New title for %s"
L["DEADPOOL_ACHIEVEMENT_WINS"] = "Winning streak"
L["DEADPOOL_ACHIEVEMENT_WINS_DESC"] = "Be the first to win %s times in the same game."
L["DEADPOOL_ACHIEVEMENT_FIRSTDEATH"] = "Fragile"
L["DEADPOOL_ACHIEVEMENT_FIRSTDEATH_DESC"] = "Be the first to die first %s times in the same game."
L["DEADPOOL_ACHIEVEMENT_CREDITSBALACE"] = "Nabob"
L["DEADPOOL_ACHIEVEMENT_CREDITSBALACE_DESC"] = "Be the first to earn %s tokens in the same game."
L["DEADPOOL_ACHIEVEMENT_LOSTITEMS"] = "All naked"
L["DEADPOOL_ACHIEVEMENT_LOSTITEMS_DESC"] = "Be the first to lose all of their clothes in the same game."
L["DEADPOOL_ACHIEVEMENT_SOLEILBET"] = "Soleîl sacrilegious"
L["DEADPOOL_ACHIEVEMENT_SOLEILBET_DESC"] = "Be the first to bet %s times on the death of %s and thus lose %s clothes as punishment in the same game."

L["MAKE_BANKER_PLAY"] = "Make %s bet"
L["MAKE_FOLLOWERS_PLAY"] = "and the followers"
L["BANKER_BET"] = "%s\nbet on %s."
L["BANKER_NO_CHIPS"] = "%s\nhas no more chips."

L["NEXT_BOSS"] = "Next boss"

end
